# Generated by Django 3.0.1 on 2020-05-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='Booth',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='list',
            name='address_english',
            field=models.CharField(blank=True, default='  ', max_length=100),
        ),
        migrations.AlterField(
            model_name='list',
            name='address_hindi',
            field=models.CharField(blank=True, default='  ', max_length=100),
        ),
        migrations.AlterField(
            model_name='list',
            name='center',
            field=models.CharField(default='  ', max_length=100),
        ),
        migrations.AlterField(
            model_name='list',
            name='dob',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='gender',
            field=models.CharField(blank=True, default='  ', max_length=100),
        ),
        migrations.AlterField(
            model_name='list',
            name='name_hindi',
            field=models.CharField(blank=True, default='  ', max_length=100),
        ),
    ]
