# Generated by Django 3.0.1 on 2020-05-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20200519_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='dob',
        ),
        migrations.AddField(
            model_name='list',
            name='name_new',
            field=models.CharField(blank=True, default='  ', max_length=100),
        ),
    ]
