# Generated by Django 3.0.1 on 2020-05-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20200520_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aligarh_c',
            fields=[
                ('list_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='list.list')),
            ],
            bases=('list.list',),
        ),
    ]
