# Generated by Django 3.0.1 on 2020-05-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20200521_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='datecompleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='Booth',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='list',
            name='section',
            field=models.IntegerField(),
        ),
    ]
