# Generated by Django 3.0.1 on 2020-05-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20200521_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='dob',
            field=models.CharField(blank=True, default='  ', max_length=20),
        ),
        migrations.AlterField(
            model_name='list',
            name='Booth',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='list',
            name='section',
            field=models.IntegerField(default=0),
        ),
    ]
