# Generated by Django 3.0.1 on 2020-05-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_auto_20200521_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='datecompleted',
        ),
    ]
