# Generated by Django 3.0.1 on 2020-05-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_remove_list_datecompleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agra',
        ),
    ]
